version: '3'

volumes:
  postgres_volume:
  redis_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    env_file:
      - .env
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - "redis_volume:/data"

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    env_file:
      - .env
    restart: on-failure
