package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/nqxcode/auth_microservice/internal/service.ProducerService -o ./mocks\producer_service_minimock.go -n ProducerServiceMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/nqxcode/auth_microservice/internal/model"
)

// ProducerServiceMock implements service.ProducerService
type ProducerServiceMock struct {
	t minimock.Tester

	funcSendMessage          func(ctx context.Context, message model.LogMessage) (err error)
	inspectFuncSendMessage   func(ctx context.Context, message model.LogMessage)
	afterSendMessageCounter  uint64
	beforeSendMessageCounter uint64
	SendMessageMock          mProducerServiceMockSendMessage
}

// NewProducerServiceMock returns a mock for service.ProducerService
func NewProducerServiceMock(t minimock.Tester) *ProducerServiceMock {
	m := &ProducerServiceMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMessageMock = mProducerServiceMockSendMessage{mock: m}
	m.SendMessageMock.callArgs = []*ProducerServiceMockSendMessageParams{}

	return m
}

type mProducerServiceMockSendMessage struct {
	mock               *ProducerServiceMock
	defaultExpectation *ProducerServiceMockSendMessageExpectation
	expectations       []*ProducerServiceMockSendMessageExpectation

	callArgs []*ProducerServiceMockSendMessageParams
	mutex    sync.RWMutex
}

// ProducerServiceMockSendMessageExpectation specifies expectation struct of the ProducerService.SendMessage
type ProducerServiceMockSendMessageExpectation struct {
	mock    *ProducerServiceMock
	params  *ProducerServiceMockSendMessageParams
	results *ProducerServiceMockSendMessageResults
	Counter uint64
}

// ProducerServiceMockSendMessageParams contains parameters of the ProducerService.SendMessage
type ProducerServiceMockSendMessageParams struct {
	ctx     context.Context
	message model.LogMessage
}

// ProducerServiceMockSendMessageResults contains results of the ProducerService.SendMessage
type ProducerServiceMockSendMessageResults struct {
	err error
}

// Expect sets up expected params for ProducerService.SendMessage
func (mmSendMessage *mProducerServiceMockSendMessage) Expect(ctx context.Context, message model.LogMessage) *mProducerServiceMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("ProducerServiceMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &ProducerServiceMockSendMessageExpectation{}
	}

	mmSendMessage.defaultExpectation.params = &ProducerServiceMockSendMessageParams{ctx, message}
	for _, e := range mmSendMessage.expectations {
		if minimock.Equal(e.params, mmSendMessage.defaultExpectation.params) {
			mmSendMessage.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendMessage.defaultExpectation.params)
		}
	}

	return mmSendMessage
}

// Inspect accepts an inspector function that has same arguments as the ProducerService.SendMessage
func (mmSendMessage *mProducerServiceMockSendMessage) Inspect(f func(ctx context.Context, message model.LogMessage)) *mProducerServiceMockSendMessage {
	if mmSendMessage.mock.inspectFuncSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("Inspect function is already set for ProducerServiceMock.SendMessage")
	}

	mmSendMessage.mock.inspectFuncSendMessage = f

	return mmSendMessage
}

// Return sets up results that will be returned by ProducerService.SendMessage
func (mmSendMessage *mProducerServiceMockSendMessage) Return(err error) *ProducerServiceMock {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("ProducerServiceMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &ProducerServiceMockSendMessageExpectation{mock: mmSendMessage.mock}
	}
	mmSendMessage.defaultExpectation.results = &ProducerServiceMockSendMessageResults{err}
	return mmSendMessage.mock
}

// Set uses given function f to mock the ProducerService.SendMessage method
func (mmSendMessage *mProducerServiceMockSendMessage) Set(f func(ctx context.Context, message model.LogMessage) (err error)) *ProducerServiceMock {
	if mmSendMessage.defaultExpectation != nil {
		mmSendMessage.mock.t.Fatalf("Default expectation is already set for the ProducerService.SendMessage method")
	}

	if len(mmSendMessage.expectations) > 0 {
		mmSendMessage.mock.t.Fatalf("Some expectations are already set for the ProducerService.SendMessage method")
	}

	mmSendMessage.mock.funcSendMessage = f
	return mmSendMessage.mock
}

// When sets expectation for the ProducerService.SendMessage which will trigger the result defined by the following
// Then helper
func (mmSendMessage *mProducerServiceMockSendMessage) When(ctx context.Context, message model.LogMessage) *ProducerServiceMockSendMessageExpectation {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("ProducerServiceMock.SendMessage mock is already set by Set")
	}

	expectation := &ProducerServiceMockSendMessageExpectation{
		mock:   mmSendMessage.mock,
		params: &ProducerServiceMockSendMessageParams{ctx, message},
	}
	mmSendMessage.expectations = append(mmSendMessage.expectations, expectation)
	return expectation
}

// Then sets up ProducerService.SendMessage return parameters for the expectation previously defined by the When method
func (e *ProducerServiceMockSendMessageExpectation) Then(err error) *ProducerServiceMock {
	e.results = &ProducerServiceMockSendMessageResults{err}
	return e.mock
}

// SendMessage implements service.ProducerService
func (mmSendMessage *ProducerServiceMock) SendMessage(ctx context.Context, message model.LogMessage) (err error) {
	mm_atomic.AddUint64(&mmSendMessage.beforeSendMessageCounter, 1)
	defer mm_atomic.AddUint64(&mmSendMessage.afterSendMessageCounter, 1)

	if mmSendMessage.inspectFuncSendMessage != nil {
		mmSendMessage.inspectFuncSendMessage(ctx, message)
	}

	mm_params := &ProducerServiceMockSendMessageParams{ctx, message}

	// Record call args
	mmSendMessage.SendMessageMock.mutex.Lock()
	mmSendMessage.SendMessageMock.callArgs = append(mmSendMessage.SendMessageMock.callArgs, mm_params)
	mmSendMessage.SendMessageMock.mutex.Unlock()

	for _, e := range mmSendMessage.SendMessageMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendMessage.SendMessageMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendMessage.SendMessageMock.defaultExpectation.Counter, 1)
		mm_want := mmSendMessage.SendMessageMock.defaultExpectation.params
		mm_got := ProducerServiceMockSendMessageParams{ctx, message}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendMessage.t.Errorf("ProducerServiceMock.SendMessage got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendMessage.SendMessageMock.defaultExpectation.results
		if mm_results == nil {
			mmSendMessage.t.Fatal("No results are set for the ProducerServiceMock.SendMessage")
		}
		return (*mm_results).err
	}
	if mmSendMessage.funcSendMessage != nil {
		return mmSendMessage.funcSendMessage(ctx, message)
	}
	mmSendMessage.t.Fatalf("Unexpected call to ProducerServiceMock.SendMessage. %v %v", ctx, message)
	return
}

// SendMessageAfterCounter returns a count of finished ProducerServiceMock.SendMessage invocations
func (mmSendMessage *ProducerServiceMock) SendMessageAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendMessage.afterSendMessageCounter)
}

// SendMessageBeforeCounter returns a count of ProducerServiceMock.SendMessage invocations
func (mmSendMessage *ProducerServiceMock) SendMessageBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendMessage.beforeSendMessageCounter)
}

// Calls returns a list of arguments used in each call to ProducerServiceMock.SendMessage.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendMessage *mProducerServiceMockSendMessage) Calls() []*ProducerServiceMockSendMessageParams {
	mmSendMessage.mutex.RLock()

	argCopy := make([]*ProducerServiceMockSendMessageParams, len(mmSendMessage.callArgs))
	copy(argCopy, mmSendMessage.callArgs)

	mmSendMessage.mutex.RUnlock()

	return argCopy
}

// MinimockSendMessageDone returns true if the count of the SendMessage invocations corresponds
// the number of defined expectations
func (m *ProducerServiceMock) MinimockSendMessageDone() bool {
	for _, e := range m.SendMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMessageMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendMessageCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendMessage != nil && mm_atomic.LoadUint64(&m.afterSendMessageCounter) < 1 {
		return false
	}
	return true
}

// MinimockSendMessageInspect logs each unmet expectation
func (m *ProducerServiceMock) MinimockSendMessageInspect() {
	for _, e := range m.SendMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProducerServiceMock.SendMessage with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMessageMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendMessageCounter) < 1 {
		if m.SendMessageMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ProducerServiceMock.SendMessage")
		} else {
			m.t.Errorf("Expected call to ProducerServiceMock.SendMessage with params: %#v", *m.SendMessageMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendMessage != nil && mm_atomic.LoadUint64(&m.afterSendMessageCounter) < 1 {
		m.t.Error("Expected call to ProducerServiceMock.SendMessage")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProducerServiceMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSendMessageInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProducerServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProducerServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendMessageDone()
}
