// Code generated by http://github.com/gojuno/minimock (v3.3.14). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/nqxcode/auth_microservice/internal/service.TokenGenerator -o token_generator_minimock.go -n TokenGeneratorMock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/nqxcode/auth_microservice/internal/model"
)

// TokenGeneratorMock implements service.TokenGenerator
type TokenGeneratorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGenerateToken          func(info model.UserInfo, secretKey []byte, duration time.Duration) (s1 string, err error)
	inspectFuncGenerateToken   func(info model.UserInfo, secretKey []byte, duration time.Duration)
	afterGenerateTokenCounter  uint64
	beforeGenerateTokenCounter uint64
	GenerateTokenMock          mTokenGeneratorMockGenerateToken
}

// NewTokenGeneratorMock returns a mock for service.TokenGenerator
func NewTokenGeneratorMock(t minimock.Tester) *TokenGeneratorMock {
	m := &TokenGeneratorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GenerateTokenMock = mTokenGeneratorMockGenerateToken{mock: m}
	m.GenerateTokenMock.callArgs = []*TokenGeneratorMockGenerateTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTokenGeneratorMockGenerateToken struct {
	optional           bool
	mock               *TokenGeneratorMock
	defaultExpectation *TokenGeneratorMockGenerateTokenExpectation
	expectations       []*TokenGeneratorMockGenerateTokenExpectation

	callArgs []*TokenGeneratorMockGenerateTokenParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// TokenGeneratorMockGenerateTokenExpectation specifies expectation struct of the TokenGenerator.GenerateToken
type TokenGeneratorMockGenerateTokenExpectation struct {
	mock      *TokenGeneratorMock
	params    *TokenGeneratorMockGenerateTokenParams
	paramPtrs *TokenGeneratorMockGenerateTokenParamPtrs
	results   *TokenGeneratorMockGenerateTokenResults
	Counter   uint64
}

// TokenGeneratorMockGenerateTokenParams contains parameters of the TokenGenerator.GenerateToken
type TokenGeneratorMockGenerateTokenParams struct {
	info      model.UserInfo
	secretKey []byte
	duration  time.Duration
}

// TokenGeneratorMockGenerateTokenParamPtrs contains pointers to parameters of the TokenGenerator.GenerateToken
type TokenGeneratorMockGenerateTokenParamPtrs struct {
	info      *model.UserInfo
	secretKey *[]byte
	duration  *time.Duration
}

// TokenGeneratorMockGenerateTokenResults contains results of the TokenGenerator.GenerateToken
type TokenGeneratorMockGenerateTokenResults struct {
	s1  string
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) Optional() *mTokenGeneratorMockGenerateToken {
	mmGenerateToken.optional = true
	return mmGenerateToken
}

// Expect sets up expected params for TokenGenerator.GenerateToken
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) Expect(info model.UserInfo, secretKey []byte, duration time.Duration) *mTokenGeneratorMockGenerateToken {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by Set")
	}

	if mmGenerateToken.defaultExpectation == nil {
		mmGenerateToken.defaultExpectation = &TokenGeneratorMockGenerateTokenExpectation{}
	}

	if mmGenerateToken.defaultExpectation.paramPtrs != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by ExpectParams functions")
	}

	mmGenerateToken.defaultExpectation.params = &TokenGeneratorMockGenerateTokenParams{info, secretKey, duration}
	for _, e := range mmGenerateToken.expectations {
		if minimock.Equal(e.params, mmGenerateToken.defaultExpectation.params) {
			mmGenerateToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGenerateToken.defaultExpectation.params)
		}
	}

	return mmGenerateToken
}

// ExpectInfoParam1 sets up expected param info for TokenGenerator.GenerateToken
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) ExpectInfoParam1(info model.UserInfo) *mTokenGeneratorMockGenerateToken {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by Set")
	}

	if mmGenerateToken.defaultExpectation == nil {
		mmGenerateToken.defaultExpectation = &TokenGeneratorMockGenerateTokenExpectation{}
	}

	if mmGenerateToken.defaultExpectation.params != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by Expect")
	}

	if mmGenerateToken.defaultExpectation.paramPtrs == nil {
		mmGenerateToken.defaultExpectation.paramPtrs = &TokenGeneratorMockGenerateTokenParamPtrs{}
	}
	mmGenerateToken.defaultExpectation.paramPtrs.info = &info

	return mmGenerateToken
}

// ExpectSecretKeyParam2 sets up expected param secretKey for TokenGenerator.GenerateToken
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) ExpectSecretKeyParam2(secretKey []byte) *mTokenGeneratorMockGenerateToken {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by Set")
	}

	if mmGenerateToken.defaultExpectation == nil {
		mmGenerateToken.defaultExpectation = &TokenGeneratorMockGenerateTokenExpectation{}
	}

	if mmGenerateToken.defaultExpectation.params != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by Expect")
	}

	if mmGenerateToken.defaultExpectation.paramPtrs == nil {
		mmGenerateToken.defaultExpectation.paramPtrs = &TokenGeneratorMockGenerateTokenParamPtrs{}
	}
	mmGenerateToken.defaultExpectation.paramPtrs.secretKey = &secretKey

	return mmGenerateToken
}

// ExpectDurationParam3 sets up expected param duration for TokenGenerator.GenerateToken
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) ExpectDurationParam3(duration time.Duration) *mTokenGeneratorMockGenerateToken {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by Set")
	}

	if mmGenerateToken.defaultExpectation == nil {
		mmGenerateToken.defaultExpectation = &TokenGeneratorMockGenerateTokenExpectation{}
	}

	if mmGenerateToken.defaultExpectation.params != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by Expect")
	}

	if mmGenerateToken.defaultExpectation.paramPtrs == nil {
		mmGenerateToken.defaultExpectation.paramPtrs = &TokenGeneratorMockGenerateTokenParamPtrs{}
	}
	mmGenerateToken.defaultExpectation.paramPtrs.duration = &duration

	return mmGenerateToken
}

// Inspect accepts an inspector function that has same arguments as the TokenGenerator.GenerateToken
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) Inspect(f func(info model.UserInfo, secretKey []byte, duration time.Duration)) *mTokenGeneratorMockGenerateToken {
	if mmGenerateToken.mock.inspectFuncGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("Inspect function is already set for TokenGeneratorMock.GenerateToken")
	}

	mmGenerateToken.mock.inspectFuncGenerateToken = f

	return mmGenerateToken
}

// Return sets up results that will be returned by TokenGenerator.GenerateToken
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) Return(s1 string, err error) *TokenGeneratorMock {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by Set")
	}

	if mmGenerateToken.defaultExpectation == nil {
		mmGenerateToken.defaultExpectation = &TokenGeneratorMockGenerateTokenExpectation{mock: mmGenerateToken.mock}
	}
	mmGenerateToken.defaultExpectation.results = &TokenGeneratorMockGenerateTokenResults{s1, err}
	return mmGenerateToken.mock
}

// Set uses given function f to mock the TokenGenerator.GenerateToken method
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) Set(f func(info model.UserInfo, secretKey []byte, duration time.Duration) (s1 string, err error)) *TokenGeneratorMock {
	if mmGenerateToken.defaultExpectation != nil {
		mmGenerateToken.mock.t.Fatalf("Default expectation is already set for the TokenGenerator.GenerateToken method")
	}

	if len(mmGenerateToken.expectations) > 0 {
		mmGenerateToken.mock.t.Fatalf("Some expectations are already set for the TokenGenerator.GenerateToken method")
	}

	mmGenerateToken.mock.funcGenerateToken = f
	return mmGenerateToken.mock
}

// When sets expectation for the TokenGenerator.GenerateToken which will trigger the result defined by the following
// Then helper
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) When(info model.UserInfo, secretKey []byte, duration time.Duration) *TokenGeneratorMockGenerateTokenExpectation {
	if mmGenerateToken.mock.funcGenerateToken != nil {
		mmGenerateToken.mock.t.Fatalf("TokenGeneratorMock.GenerateToken mock is already set by Set")
	}

	expectation := &TokenGeneratorMockGenerateTokenExpectation{
		mock:   mmGenerateToken.mock,
		params: &TokenGeneratorMockGenerateTokenParams{info, secretKey, duration},
	}
	mmGenerateToken.expectations = append(mmGenerateToken.expectations, expectation)
	return expectation
}

// Then sets up TokenGenerator.GenerateToken return parameters for the expectation previously defined by the When method
func (e *TokenGeneratorMockGenerateTokenExpectation) Then(s1 string, err error) *TokenGeneratorMock {
	e.results = &TokenGeneratorMockGenerateTokenResults{s1, err}
	return e.mock
}

// Times sets number of times TokenGenerator.GenerateToken should be invoked
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) Times(n uint64) *mTokenGeneratorMockGenerateToken {
	if n == 0 {
		mmGenerateToken.mock.t.Fatalf("Times of TokenGeneratorMock.GenerateToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGenerateToken.expectedInvocations, n)
	return mmGenerateToken
}

func (mmGenerateToken *mTokenGeneratorMockGenerateToken) invocationsDone() bool {
	if len(mmGenerateToken.expectations) == 0 && mmGenerateToken.defaultExpectation == nil && mmGenerateToken.mock.funcGenerateToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGenerateToken.mock.afterGenerateTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGenerateToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GenerateToken implements service.TokenGenerator
func (mmGenerateToken *TokenGeneratorMock) GenerateToken(info model.UserInfo, secretKey []byte, duration time.Duration) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGenerateToken.beforeGenerateTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGenerateToken.afterGenerateTokenCounter, 1)

	if mmGenerateToken.inspectFuncGenerateToken != nil {
		mmGenerateToken.inspectFuncGenerateToken(info, secretKey, duration)
	}

	mm_params := TokenGeneratorMockGenerateTokenParams{info, secretKey, duration}

	// Record call args
	mmGenerateToken.GenerateTokenMock.mutex.Lock()
	mmGenerateToken.GenerateTokenMock.callArgs = append(mmGenerateToken.GenerateTokenMock.callArgs, &mm_params)
	mmGenerateToken.GenerateTokenMock.mutex.Unlock()

	for _, e := range mmGenerateToken.GenerateTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGenerateToken.GenerateTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGenerateToken.GenerateTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGenerateToken.GenerateTokenMock.defaultExpectation.params
		mm_want_ptrs := mmGenerateToken.GenerateTokenMock.defaultExpectation.paramPtrs

		mm_got := TokenGeneratorMockGenerateTokenParams{info, secretKey, duration}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.info != nil && !minimock.Equal(*mm_want_ptrs.info, mm_got.info) {
				mmGenerateToken.t.Errorf("TokenGeneratorMock.GenerateToken got unexpected parameter info, want: %#v, got: %#v%s\n", *mm_want_ptrs.info, mm_got.info, minimock.Diff(*mm_want_ptrs.info, mm_got.info))
			}

			if mm_want_ptrs.secretKey != nil && !minimock.Equal(*mm_want_ptrs.secretKey, mm_got.secretKey) {
				mmGenerateToken.t.Errorf("TokenGeneratorMock.GenerateToken got unexpected parameter secretKey, want: %#v, got: %#v%s\n", *mm_want_ptrs.secretKey, mm_got.secretKey, minimock.Diff(*mm_want_ptrs.secretKey, mm_got.secretKey))
			}

			if mm_want_ptrs.duration != nil && !minimock.Equal(*mm_want_ptrs.duration, mm_got.duration) {
				mmGenerateToken.t.Errorf("TokenGeneratorMock.GenerateToken got unexpected parameter duration, want: %#v, got: %#v%s\n", *mm_want_ptrs.duration, mm_got.duration, minimock.Diff(*mm_want_ptrs.duration, mm_got.duration))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGenerateToken.t.Errorf("TokenGeneratorMock.GenerateToken got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGenerateToken.GenerateTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGenerateToken.t.Fatal("No results are set for the TokenGeneratorMock.GenerateToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGenerateToken.funcGenerateToken != nil {
		return mmGenerateToken.funcGenerateToken(info, secretKey, duration)
	}
	mmGenerateToken.t.Fatalf("Unexpected call to TokenGeneratorMock.GenerateToken. %v %v %v", info, secretKey, duration)
	return
}

// GenerateTokenAfterCounter returns a count of finished TokenGeneratorMock.GenerateToken invocations
func (mmGenerateToken *TokenGeneratorMock) GenerateTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateToken.afterGenerateTokenCounter)
}

// GenerateTokenBeforeCounter returns a count of TokenGeneratorMock.GenerateToken invocations
func (mmGenerateToken *TokenGeneratorMock) GenerateTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateToken.beforeGenerateTokenCounter)
}

// Calls returns a list of arguments used in each call to TokenGeneratorMock.GenerateToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGenerateToken *mTokenGeneratorMockGenerateToken) Calls() []*TokenGeneratorMockGenerateTokenParams {
	mmGenerateToken.mutex.RLock()

	argCopy := make([]*TokenGeneratorMockGenerateTokenParams, len(mmGenerateToken.callArgs))
	copy(argCopy, mmGenerateToken.callArgs)

	mmGenerateToken.mutex.RUnlock()

	return argCopy
}

// MinimockGenerateTokenDone returns true if the count of the GenerateToken invocations corresponds
// the number of defined expectations
func (m *TokenGeneratorMock) MinimockGenerateTokenDone() bool {
	if m.GenerateTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GenerateTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GenerateTokenMock.invocationsDone()
}

// MinimockGenerateTokenInspect logs each unmet expectation
func (m *TokenGeneratorMock) MinimockGenerateTokenInspect() {
	for _, e := range m.GenerateTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenGeneratorMock.GenerateToken with params: %#v", *e.params)
		}
	}

	afterGenerateTokenCounter := mm_atomic.LoadUint64(&m.afterGenerateTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateTokenMock.defaultExpectation != nil && afterGenerateTokenCounter < 1 {
		if m.GenerateTokenMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to TokenGeneratorMock.GenerateToken")
		} else {
			m.t.Errorf("Expected call to TokenGeneratorMock.GenerateToken with params: %#v", *m.GenerateTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateToken != nil && afterGenerateTokenCounter < 1 {
		m.t.Error("Expected call to TokenGeneratorMock.GenerateToken")
	}

	if !m.GenerateTokenMock.invocationsDone() && afterGenerateTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to TokenGeneratorMock.GenerateToken but found %d calls",
			mm_atomic.LoadUint64(&m.GenerateTokenMock.expectedInvocations), afterGenerateTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TokenGeneratorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGenerateTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TokenGeneratorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TokenGeneratorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGenerateTokenDone()
}
