// Code generated by http://github.com/gojuno/minimock (v3.3.14). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/nqxcode/auth_microservice/internal/service.ValidatorService -o validator_service_minimock.go -n ValidatorServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/nqxcode/auth_microservice/internal/model"
)

// ValidatorServiceMock implements service.ValidatorService
type ValidatorServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcValidateUser          func(ctx context.Context, userInfo model.UserInfo, password string, passwordConfirm string) (err error)
	inspectFuncValidateUser   func(ctx context.Context, userInfo model.UserInfo, password string, passwordConfirm string)
	afterValidateUserCounter  uint64
	beforeValidateUserCounter uint64
	ValidateUserMock          mValidatorServiceMockValidateUser
}

// NewValidatorServiceMock returns a mock for service.ValidatorService
func NewValidatorServiceMock(t minimock.Tester) *ValidatorServiceMock {
	m := &ValidatorServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ValidateUserMock = mValidatorServiceMockValidateUser{mock: m}
	m.ValidateUserMock.callArgs = []*ValidatorServiceMockValidateUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mValidatorServiceMockValidateUser struct {
	optional           bool
	mock               *ValidatorServiceMock
	defaultExpectation *ValidatorServiceMockValidateUserExpectation
	expectations       []*ValidatorServiceMockValidateUserExpectation

	callArgs []*ValidatorServiceMockValidateUserParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// ValidatorServiceMockValidateUserExpectation specifies expectation struct of the ValidatorService.ValidateUser
type ValidatorServiceMockValidateUserExpectation struct {
	mock      *ValidatorServiceMock
	params    *ValidatorServiceMockValidateUserParams
	paramPtrs *ValidatorServiceMockValidateUserParamPtrs
	results   *ValidatorServiceMockValidateUserResults
	Counter   uint64
}

// ValidatorServiceMockValidateUserParams contains parameters of the ValidatorService.ValidateUser
type ValidatorServiceMockValidateUserParams struct {
	ctx             context.Context
	userInfo        model.UserInfo
	password        string
	passwordConfirm string
}

// ValidatorServiceMockValidateUserParamPtrs contains pointers to parameters of the ValidatorService.ValidateUser
type ValidatorServiceMockValidateUserParamPtrs struct {
	ctx             *context.Context
	userInfo        *model.UserInfo
	password        *string
	passwordConfirm *string
}

// ValidatorServiceMockValidateUserResults contains results of the ValidatorService.ValidateUser
type ValidatorServiceMockValidateUserResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmValidateUser *mValidatorServiceMockValidateUser) Optional() *mValidatorServiceMockValidateUser {
	mmValidateUser.optional = true
	return mmValidateUser
}

// Expect sets up expected params for ValidatorService.ValidateUser
func (mmValidateUser *mValidatorServiceMockValidateUser) Expect(ctx context.Context, userInfo model.UserInfo, password string, passwordConfirm string) *mValidatorServiceMockValidateUser {
	if mmValidateUser.mock.funcValidateUser != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Set")
	}

	if mmValidateUser.defaultExpectation == nil {
		mmValidateUser.defaultExpectation = &ValidatorServiceMockValidateUserExpectation{}
	}

	if mmValidateUser.defaultExpectation.paramPtrs != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by ExpectParams functions")
	}

	mmValidateUser.defaultExpectation.params = &ValidatorServiceMockValidateUserParams{ctx, userInfo, password, passwordConfirm}
	for _, e := range mmValidateUser.expectations {
		if minimock.Equal(e.params, mmValidateUser.defaultExpectation.params) {
			mmValidateUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmValidateUser.defaultExpectation.params)
		}
	}

	return mmValidateUser
}

// ExpectCtxParam1 sets up expected param ctx for ValidatorService.ValidateUser
func (mmValidateUser *mValidatorServiceMockValidateUser) ExpectCtxParam1(ctx context.Context) *mValidatorServiceMockValidateUser {
	if mmValidateUser.mock.funcValidateUser != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Set")
	}

	if mmValidateUser.defaultExpectation == nil {
		mmValidateUser.defaultExpectation = &ValidatorServiceMockValidateUserExpectation{}
	}

	if mmValidateUser.defaultExpectation.params != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Expect")
	}

	if mmValidateUser.defaultExpectation.paramPtrs == nil {
		mmValidateUser.defaultExpectation.paramPtrs = &ValidatorServiceMockValidateUserParamPtrs{}
	}
	mmValidateUser.defaultExpectation.paramPtrs.ctx = &ctx

	return mmValidateUser
}

// ExpectUserInfoParam2 sets up expected param userInfo for ValidatorService.ValidateUser
func (mmValidateUser *mValidatorServiceMockValidateUser) ExpectUserInfoParam2(userInfo model.UserInfo) *mValidatorServiceMockValidateUser {
	if mmValidateUser.mock.funcValidateUser != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Set")
	}

	if mmValidateUser.defaultExpectation == nil {
		mmValidateUser.defaultExpectation = &ValidatorServiceMockValidateUserExpectation{}
	}

	if mmValidateUser.defaultExpectation.params != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Expect")
	}

	if mmValidateUser.defaultExpectation.paramPtrs == nil {
		mmValidateUser.defaultExpectation.paramPtrs = &ValidatorServiceMockValidateUserParamPtrs{}
	}
	mmValidateUser.defaultExpectation.paramPtrs.userInfo = &userInfo

	return mmValidateUser
}

// ExpectPasswordParam3 sets up expected param password for ValidatorService.ValidateUser
func (mmValidateUser *mValidatorServiceMockValidateUser) ExpectPasswordParam3(password string) *mValidatorServiceMockValidateUser {
	if mmValidateUser.mock.funcValidateUser != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Set")
	}

	if mmValidateUser.defaultExpectation == nil {
		mmValidateUser.defaultExpectation = &ValidatorServiceMockValidateUserExpectation{}
	}

	if mmValidateUser.defaultExpectation.params != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Expect")
	}

	if mmValidateUser.defaultExpectation.paramPtrs == nil {
		mmValidateUser.defaultExpectation.paramPtrs = &ValidatorServiceMockValidateUserParamPtrs{}
	}
	mmValidateUser.defaultExpectation.paramPtrs.password = &password

	return mmValidateUser
}

// ExpectPasswordConfirmParam4 sets up expected param passwordConfirm for ValidatorService.ValidateUser
func (mmValidateUser *mValidatorServiceMockValidateUser) ExpectPasswordConfirmParam4(passwordConfirm string) *mValidatorServiceMockValidateUser {
	if mmValidateUser.mock.funcValidateUser != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Set")
	}

	if mmValidateUser.defaultExpectation == nil {
		mmValidateUser.defaultExpectation = &ValidatorServiceMockValidateUserExpectation{}
	}

	if mmValidateUser.defaultExpectation.params != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Expect")
	}

	if mmValidateUser.defaultExpectation.paramPtrs == nil {
		mmValidateUser.defaultExpectation.paramPtrs = &ValidatorServiceMockValidateUserParamPtrs{}
	}
	mmValidateUser.defaultExpectation.paramPtrs.passwordConfirm = &passwordConfirm

	return mmValidateUser
}

// Inspect accepts an inspector function that has same arguments as the ValidatorService.ValidateUser
func (mmValidateUser *mValidatorServiceMockValidateUser) Inspect(f func(ctx context.Context, userInfo model.UserInfo, password string, passwordConfirm string)) *mValidatorServiceMockValidateUser {
	if mmValidateUser.mock.inspectFuncValidateUser != nil {
		mmValidateUser.mock.t.Fatalf("Inspect function is already set for ValidatorServiceMock.ValidateUser")
	}

	mmValidateUser.mock.inspectFuncValidateUser = f

	return mmValidateUser
}

// Return sets up results that will be returned by ValidatorService.ValidateUser
func (mmValidateUser *mValidatorServiceMockValidateUser) Return(err error) *ValidatorServiceMock {
	if mmValidateUser.mock.funcValidateUser != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Set")
	}

	if mmValidateUser.defaultExpectation == nil {
		mmValidateUser.defaultExpectation = &ValidatorServiceMockValidateUserExpectation{mock: mmValidateUser.mock}
	}
	mmValidateUser.defaultExpectation.results = &ValidatorServiceMockValidateUserResults{err}
	return mmValidateUser.mock
}

// Set uses given function f to mock the ValidatorService.ValidateUser method
func (mmValidateUser *mValidatorServiceMockValidateUser) Set(f func(ctx context.Context, userInfo model.UserInfo, password string, passwordConfirm string) (err error)) *ValidatorServiceMock {
	if mmValidateUser.defaultExpectation != nil {
		mmValidateUser.mock.t.Fatalf("Default expectation is already set for the ValidatorService.ValidateUser method")
	}

	if len(mmValidateUser.expectations) > 0 {
		mmValidateUser.mock.t.Fatalf("Some expectations are already set for the ValidatorService.ValidateUser method")
	}

	mmValidateUser.mock.funcValidateUser = f
	return mmValidateUser.mock
}

// When sets expectation for the ValidatorService.ValidateUser which will trigger the result defined by the following
// Then helper
func (mmValidateUser *mValidatorServiceMockValidateUser) When(ctx context.Context, userInfo model.UserInfo, password string, passwordConfirm string) *ValidatorServiceMockValidateUserExpectation {
	if mmValidateUser.mock.funcValidateUser != nil {
		mmValidateUser.mock.t.Fatalf("ValidatorServiceMock.ValidateUser mock is already set by Set")
	}

	expectation := &ValidatorServiceMockValidateUserExpectation{
		mock:   mmValidateUser.mock,
		params: &ValidatorServiceMockValidateUserParams{ctx, userInfo, password, passwordConfirm},
	}
	mmValidateUser.expectations = append(mmValidateUser.expectations, expectation)
	return expectation
}

// Then sets up ValidatorService.ValidateUser return parameters for the expectation previously defined by the When method
func (e *ValidatorServiceMockValidateUserExpectation) Then(err error) *ValidatorServiceMock {
	e.results = &ValidatorServiceMockValidateUserResults{err}
	return e.mock
}

// Times sets number of times ValidatorService.ValidateUser should be invoked
func (mmValidateUser *mValidatorServiceMockValidateUser) Times(n uint64) *mValidatorServiceMockValidateUser {
	if n == 0 {
		mmValidateUser.mock.t.Fatalf("Times of ValidatorServiceMock.ValidateUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmValidateUser.expectedInvocations, n)
	return mmValidateUser
}

func (mmValidateUser *mValidatorServiceMockValidateUser) invocationsDone() bool {
	if len(mmValidateUser.expectations) == 0 && mmValidateUser.defaultExpectation == nil && mmValidateUser.mock.funcValidateUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmValidateUser.mock.afterValidateUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmValidateUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ValidateUser implements service.ValidatorService
func (mmValidateUser *ValidatorServiceMock) ValidateUser(ctx context.Context, userInfo model.UserInfo, password string, passwordConfirm string) (err error) {
	mm_atomic.AddUint64(&mmValidateUser.beforeValidateUserCounter, 1)
	defer mm_atomic.AddUint64(&mmValidateUser.afterValidateUserCounter, 1)

	if mmValidateUser.inspectFuncValidateUser != nil {
		mmValidateUser.inspectFuncValidateUser(ctx, userInfo, password, passwordConfirm)
	}

	mm_params := ValidatorServiceMockValidateUserParams{ctx, userInfo, password, passwordConfirm}

	// Record call args
	mmValidateUser.ValidateUserMock.mutex.Lock()
	mmValidateUser.ValidateUserMock.callArgs = append(mmValidateUser.ValidateUserMock.callArgs, &mm_params)
	mmValidateUser.ValidateUserMock.mutex.Unlock()

	for _, e := range mmValidateUser.ValidateUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmValidateUser.ValidateUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmValidateUser.ValidateUserMock.defaultExpectation.Counter, 1)
		mm_want := mmValidateUser.ValidateUserMock.defaultExpectation.params
		mm_want_ptrs := mmValidateUser.ValidateUserMock.defaultExpectation.paramPtrs

		mm_got := ValidatorServiceMockValidateUserParams{ctx, userInfo, password, passwordConfirm}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmValidateUser.t.Errorf("ValidatorServiceMock.ValidateUser got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userInfo != nil && !minimock.Equal(*mm_want_ptrs.userInfo, mm_got.userInfo) {
				mmValidateUser.t.Errorf("ValidatorServiceMock.ValidateUser got unexpected parameter userInfo, want: %#v, got: %#v%s\n", *mm_want_ptrs.userInfo, mm_got.userInfo, minimock.Diff(*mm_want_ptrs.userInfo, mm_got.userInfo))
			}

			if mm_want_ptrs.password != nil && !minimock.Equal(*mm_want_ptrs.password, mm_got.password) {
				mmValidateUser.t.Errorf("ValidatorServiceMock.ValidateUser got unexpected parameter password, want: %#v, got: %#v%s\n", *mm_want_ptrs.password, mm_got.password, minimock.Diff(*mm_want_ptrs.password, mm_got.password))
			}

			if mm_want_ptrs.passwordConfirm != nil && !minimock.Equal(*mm_want_ptrs.passwordConfirm, mm_got.passwordConfirm) {
				mmValidateUser.t.Errorf("ValidatorServiceMock.ValidateUser got unexpected parameter passwordConfirm, want: %#v, got: %#v%s\n", *mm_want_ptrs.passwordConfirm, mm_got.passwordConfirm, minimock.Diff(*mm_want_ptrs.passwordConfirm, mm_got.passwordConfirm))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmValidateUser.t.Errorf("ValidatorServiceMock.ValidateUser got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmValidateUser.ValidateUserMock.defaultExpectation.results
		if mm_results == nil {
			mmValidateUser.t.Fatal("No results are set for the ValidatorServiceMock.ValidateUser")
		}
		return (*mm_results).err
	}
	if mmValidateUser.funcValidateUser != nil {
		return mmValidateUser.funcValidateUser(ctx, userInfo, password, passwordConfirm)
	}
	mmValidateUser.t.Fatalf("Unexpected call to ValidatorServiceMock.ValidateUser. %v %v %v %v", ctx, userInfo, password, passwordConfirm)
	return
}

// ValidateUserAfterCounter returns a count of finished ValidatorServiceMock.ValidateUser invocations
func (mmValidateUser *ValidatorServiceMock) ValidateUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateUser.afterValidateUserCounter)
}

// ValidateUserBeforeCounter returns a count of ValidatorServiceMock.ValidateUser invocations
func (mmValidateUser *ValidatorServiceMock) ValidateUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateUser.beforeValidateUserCounter)
}

// Calls returns a list of arguments used in each call to ValidatorServiceMock.ValidateUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmValidateUser *mValidatorServiceMockValidateUser) Calls() []*ValidatorServiceMockValidateUserParams {
	mmValidateUser.mutex.RLock()

	argCopy := make([]*ValidatorServiceMockValidateUserParams, len(mmValidateUser.callArgs))
	copy(argCopy, mmValidateUser.callArgs)

	mmValidateUser.mutex.RUnlock()

	return argCopy
}

// MinimockValidateUserDone returns true if the count of the ValidateUser invocations corresponds
// the number of defined expectations
func (m *ValidatorServiceMock) MinimockValidateUserDone() bool {
	if m.ValidateUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ValidateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ValidateUserMock.invocationsDone()
}

// MinimockValidateUserInspect logs each unmet expectation
func (m *ValidatorServiceMock) MinimockValidateUserInspect() {
	for _, e := range m.ValidateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ValidatorServiceMock.ValidateUser with params: %#v", *e.params)
		}
	}

	afterValidateUserCounter := mm_atomic.LoadUint64(&m.afterValidateUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ValidateUserMock.defaultExpectation != nil && afterValidateUserCounter < 1 {
		if m.ValidateUserMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ValidatorServiceMock.ValidateUser")
		} else {
			m.t.Errorf("Expected call to ValidatorServiceMock.ValidateUser with params: %#v", *m.ValidateUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcValidateUser != nil && afterValidateUserCounter < 1 {
		m.t.Error("Expected call to ValidatorServiceMock.ValidateUser")
	}

	if !m.ValidateUserMock.invocationsDone() && afterValidateUserCounter > 0 {
		m.t.Errorf("Expected %d calls to ValidatorServiceMock.ValidateUser but found %d calls",
			mm_atomic.LoadUint64(&m.ValidateUserMock.expectedInvocations), afterValidateUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ValidatorServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockValidateUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ValidatorServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ValidatorServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockValidateUserDone()
}
